name: Generate Private Language Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs automatically every midnight
  workflow_dispatch: # Allows you to trigger it manually

permissions:
  contents: write # Crucial: Allows the action to commit the image back to the repo

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: StefVuck/Github-Language-Stats@v1.2.0
        with:
          github_token: ${{ secrets.STATS_TOKEN }}
          visualization_types: "leaderboard" # Other options: "bar", "pie", "donut"
